name: Build Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - ActorBasePerkFix
          - ActorLimitFix
          - BarterLimitFix
          - BugFixesSSE
          - ConditionsTargetMagicEffects
          - ConsoleCommandCompanion
          - LogInventoryItemRotation
          - PickpocketChanceFix
          - ScrambledBugs
          - ScriptEffectArchetypeCrashFix
          - Trails
          - VendorRespawnFix

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Bootstrap vcpkg
        run: |
          git clone
